# Generated by Django 4.1.5 on 2023-02-08 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Studentmd_details',
            fields=[
                ('Std_Id', models.CharField(max_length=260, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=260)),
                ('Age', models.PositiveIntegerField()),
                ('Gender', models.CharField(max_length=100)),
                ('Phone', models.PositiveSmallIntegerField()),
                ('Email', models.EmailField(max_length=254)),
            ],
        ),
    ]
